// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhiCixe7rB98RcCpFv4u8tU_HVBCHR6Wg',
    appId: '1:33879993338:web:6c6809c212db74529a9243',
    messagingSenderId: '33879993338',
    projectId: 'botom-1c53a',
    authDomain: 'botom-1c53a.firebaseapp.com',
    storageBucket: 'botom-1c53a.firebasestorage.app',
    measurementId: 'G-SB3QZG3WG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYqGXPZE69bKfJw-WWVpKQB_msoGjlr4E',
    appId: '1:33879993338:android:419cec944163a5c79a9243',
    messagingSenderId: '33879993338',
    projectId: 'botom-1c53a',
    storageBucket: 'botom-1c53a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhiCixe7rB98RcCpFv4u8tU_HVBCHR6Wg',
    appId: '1:33879993338:web:e4246ac320346fd19a9243',
    messagingSenderId: '33879993338',
    projectId: 'botom-1c53a',
    authDomain: 'botom-1c53a.firebaseapp.com',
    storageBucket: 'botom-1c53a.firebasestorage.app',
    measurementId: 'G-6KY7V70CDC',
  );

}